version: "2"
linters:
  enable:
    - ginkgolinter
    - godot
    - godox
    - importas
    - nlreturn
    - nonamedreturns
    - prealloc
    - predeclared
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - wrapcheck
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
