disabled_rules:
  - cyclomatic_complexity
  - type_body_length
  - identifier_name
  - function_body_length

opt_in_rules:
  - multiline_function_chains
  - anyobject_protocol
  - overridden_super_call
  - prohibited_super_call
  - last_where
  - contains_over_first_not_nil
  - vertical_parameter_alignment_on_call
  - multiline_arguments
  - multiline_literal_brackets
  - closure_end_indentation
  - collection_alignment
  - reduce_into
  - explicit_init
  - static_operator
  - sorted_first_last
  - no_space_in_method_call
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_collection_literal
  - empty_count

type_name:
    validates_start_with_lowercase: false

nesting:
  type_level:
    warning: 3

line_length:
  warning: 120
  error: 120
  ignore_comments: true
  ignore_urls: true

file_length:
  warning: 1000
  error: 1000

reporter: "xcode"
