name: Distribute

on:
  push:
    tags:
      - "v*"

jobs:
  get_version:
    name: Get version
    runs-on: ubuntu-20.04
    steps:
      - name: Set output
        id: set_output
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
    outputs:
      version: ${{ steps.set_output.outputs.version }}
  test:
    name: Run tests
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache SwiftPM packages
        uses: actions/cache@v3
        with:
          path: .build/checkouts
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
            ${{ runner.os }}-spm-
      - name: Inject version
        run: ./Scripts/version
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
  build:
    name: Build
    runs-on: macos-12
    needs: [get_version, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache SwiftPM packages
        uses: actions/cache@v3
        with:
          path: .build/checkouts
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
            ${{ runner.os }}-spm-
      - name: Inject version
        run: ./Scripts/version
      - name: Build
        run: make build
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ipatool-v${{ needs.get_version.outputs.version }}
          path: .build/apple/Products/Release/ipatool
          if-no-files-found: error
  distribute:
    name: Distribute
    runs-on: ubuntu-20.04
    needs: [get_version, build]
    steps:
      - name: Download binary
        uses: actions/download-artifact@v2
        with:
          name: ipatool-v${{ needs.get_version.outputs.version }}
          path: ipatool-v${{ needs.get_version.outputs.version }}
      - name: Archive binary
        run: |
          mv ipatool-v${{ needs.get_version.outputs.version }}/ipatool ipatool
          zip ipatool-v${{ needs.get_version.outputs.version }}.zip ipatool
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ipatool-v${{ needs.get_version.outputs.version }}.zip
          asset_name: ipatool-v${{ needs.get_version.outputs.version }}.zip
          tag: ${{ github.ref }}
          overwrite: false
      - name: Checkout homebrew repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.HOMEBREW_REPO }}
          path: repo
          ref: main
          token: ${{ secrets.GH_TOKEN }}
      - name: Update homebrew repo
        run: |
          SHA256=$(sha256sum ipatool-v${{ needs.get_version.outputs.version }}.zip | awk '{print $1}')
          cd repo
          sed -i "3s/.*/  sha256 \"$SHA256\"/" Casks/ipatool.rb
          sed -i "2s/.*/  version \"${{ needs.get_version.outputs.version }}\"/" Casks/ipatool.rb
          git config --local user.name ${{ secrets.GH_NAME }}
          git config --local user.email ${{ secrets.GH_EMAIL }}
          git add Casks/ipatool.rb
          git commit -m "Update ipatool to v${{ needs.get_version.outputs.version }}"
          git push "https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.HOMEBREW_REPO }}.git" --set-upstream "main"
