name: Dry Build

on:
  pull_request:
    branches:
      - main

jobs:
  build_windows:
    name: Build for Windows
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64, amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "1.23.0"
          cache: true
      - run: go build -o ipatool-$GOOS-$GOARCH.exe
        env:
          GOOS: windows
          GOARCH: ${{ matrix.arch }}
  build_linux:
    name: Build for Linux
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64, amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "1.23.0"
          cache: true
      - run: go build -o ipatool-$GOOS-$GOARCH
        env:
          GOOS: linux
          GOARCH: ${{ matrix.arch }}
  build_macos:
    name: Build for macOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64, amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "1.23.0"
          cache: true
      - run: go build -o ipatool-$GOOS-$GOARCH
        env:
          GOOS: darwin
          GOARCH: ${{ matrix.arch }}
          CGO_CFLAGS: -mmacosx-version-min=10.15
          CGO_LDFLAGS: -mmacosx-version-min=10.15
