name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "1.23.0"
          cache: true
      - run: go generate github.com/majd/ipatool/...
      - uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
